/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example;

import com.beans.DatabaseValues;
import com.beans.ProductBean;
import com.utils.DbUtil;
import com.utils.PropertiesReader;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEELA_kpwhyff
 */
public class SalePage extends javax.swing.JFrame {

    /**
     * Creates new form SalePage
     */
    ArrayList<ProductBean> productlist;
    DatabaseValues dbvalues;
    String username;

    public SalePage(String userName) {
        this.username = userName;
        con = DbUtil.getDbConnection();
        props = PropertiesReader.readPropertiesFile();
        initComponents();
        jLabel1.setText("Store Front – Sales Personnel Login (" + username + ")");
        SimpleDateFormat formatter = new SimpleDateFormat("dd MMMM yyyy");
        Date date = new Date();
        jLabel2.setText("Today's Date : " + formatter.format(date));
        table_update();
        productlist = new ArrayList<>();
        dbvalues = new DatabaseValues();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        validateAdmin();

    }

    public void validateAdmin() {
        if (!username.equals(props.getProperty("adminname"))) {
            jButton3.setVisible(false);
        }
    }

    public SalePage() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sales-Front");

        jLabel2.setText("Date");

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Place Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Admin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(59, 59, 59))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "productid", "productname", "price", "quantity", "barcode", "desc", "unreason"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str1 = JOptionPane.showInputDialog("Please enter product number");

        int k = 0;
        if (str1 != null && !(str1.equals(""))) {
            while (k != 1) {
                try {

                    int productid = Integer.parseInt(str1);

                    k = 1;

                    System.out.println(productid);
                    initialcheck(productid);
                    if (!productlist.isEmpty()) {
                        System.out.println(productlist.size() + "size");
                        ArrayList<Integer> productidslist = new ArrayList<>();

                        for (ProductBean bean : productlist) {
                            if (bean.getProductid() == productid) {
                                if (dbvalues.getDbquantity() <= bean.getCounter()) {
                                    dbvalues.setOverflow(true);
                                }
                            }
                            productidslist.add(bean.getProductid());
                        }
                        if (!dbvalues.isOverflow()) {

                            if (productidslist.contains(productid)) {
                                for (ProductBean bean : productlist) {

                                    if (bean.getProductid() == productid) {
                                        bean.setCounter(1);
                                    }
                                }
                            } else {
                                addProduct(productid);
                            }
                        } else {
                            showwarnmessage("you have exceeded items");
                        }
                    } else if (dbvalues.getDbquantity() > 0) {

                        addProduct(productid);
                    } else {
                        showwarnmessage("out of stock");
                    }

                } catch (NumberFormatException e) {
                    k = 0;
                    str1 = JOptionPane.showInputDialog("Please enter Valid number");
                    if (str1 == null || str1.equals("")) {
                        k = 1;
                    }

                }
            }
        } else if (str1.equals("")) {
            JOptionPane.showMessageDialog(null, "please enter valid data");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public void showwarnmessage(String message) {
        JOptionPane.showConfirmDialog(null, message, "Select an Option...",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
    }

    public void initialcheck(int productid) {
        try {
            ResultSet result = DbUtil.getQueryResult(props.getProperty("selecctedproductquery") + productid, con);
            while (result.next()) {
                dbvalues.setDbquantity(result.getInt("quantity"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SalePage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void addProduct(int productid) {
        try {
            ResultSet result = DbUtil.getQueryResult(props.getProperty("selecctedproductquery") + productid, con);
            while (result.next()) {

                ProductBean bean = new ProductBean();

                dbvalues.setDbquantity(result.getInt("quantity"));
                bean.setProductid(result.getInt("productid"));
                bean.setProductname(result.getString("productname"));
                bean.setPrice(result.getDouble("price"));
                bean.setQuantity(result.getInt("quantity"));
                bean.setBarcode(result.getString("barcodenum"));
                bean.setDescription(result.getString("description"));
                bean.setUnreason(result.getString("unreason"));
                bean.setCounter(1);
                bean.setExist(true);

                productlist.add(bean);

                System.out.println(bean);

            }
        } catch (SQLException ex) {
            Logger.getLogger(SalePage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO Finalorderadd your handling code here:
        if (productlist.size() != 0) {
            this.dispose();
            FinalOrderPage fp = new FinalOrderPage(productlist, username);
            //fp.addproducts(productlist);
            this.setEnabled(false);
            fp.setExtendedState(JFrame.MAXIMIZED_BOTH);
            fp.setVisible(true);
        } else {
            showwarnmessage("hey you dont selected items please select items to place order :)");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminPage adminPage = new AdminPage(username);
        adminPage.setExtendedState(JFrame.MAXIMIZED_BOTH);
        adminPage.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalePage().setVisible(true);
            }
        });
    }
    Connection con = null;
    Properties props;

    private void table_update() {
        int CC;
        try {
            ResultSet Rs = DbUtil.getQueryResult(props.getProperty("productsquery"), con);

            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            jTable1.setRowHeight(30);
            jTable1.setEnabled(false);

            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getInt("productid"));
                    v2.add(Rs.getString("productname"));
                    v2.add(Rs.getDouble("price"));
                    v2.add(Rs.getInt("quantity"));
                    v2.add(Rs.getString("barcodenum"));
                    v2.add(Rs.getString("description"));
                    v2.add(Rs.getString("unreason"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
